### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSLVERSION_TLSv1_0'

### ISSUE THREAD

**Issue by erichuang1933** [epsylon/xsser#29]
Traceback (most recent call last):
  File "./xsser", line 37, in <module>
    app.run()
  File "/Users/erichuang1933/script/xsser/xsser/core/main.py", line 2010, in run
    self.print_results()
  File "/Users/erichuang1933/script/xsser/xsser/core/main.py", line 2612, in print_results
    c = Curl()
  File "/Users/erichuang1933/script/xsser/xsser/core/curlcontrol.py", line 76, in __init__
    self.set_option(pycurl.SSLVERSION, pycurl.SSLVERSION_TLSv1_0)
AttributeError: 'module' object has no attribute 'SSLVERSION_TLSv1_0'

**Comment by epsylon** [comment]
https://stackoverflow.com/questions/35317317/python-2-7-6-tlsv1-2-in-requests

Are you using Ubuntu?... On that case:

https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1443704

You should upgrade your python version to: > 2.7.9

**Comment by epsylon** [comment]
Hey,
I have added a patch to support more SSL protocols (even those that are deprecated) so probably you will not need to upgrade your python version. Btw, try it...

https://github.com/epsylon/xsser/commit/f5b07cb592a6e2146becf6f72ee11a4b7fcc9ec0
