### ISSUE TITLE
Xsser not running

### ISSUE THREAD

**Issue by Sydwicked** [epsylon/xsser#32]
Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

root@kali:~/xsser/xsser# xsser --update
Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 4, in <module>
    __import__('pkg_resources').run_script('xsser==1.7', 'xsser')
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 661, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1441, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/xsser-1.7-py3.6.egg/EGG-INFO/scripts/xsser", line 24, in <module>
    from core.main import xsser
  File "/usr/local/lib/python3.6/dist-packages/xsser-1.7-py3.6.egg/core/main.py", line 234
    print msg
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(msg)?

**Comment by epsylon** [comment]
Hi,
That's because you are using Python v3.6 which isn't supported by XSSer.
Please try it with a different version related with the branch: v2.7.x
https://xsser.03c8.net/#installation
Ex: python2.7 xsser --update
