### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Sy3Omda** [epsylon/xsser#36]
OS : kali linux 2019
# xsser --gtk

`Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 4, in <module>
    __import__('pkg_resources').run_script('xsser==1.7', 'xsser')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/xsser-1.7-py2.7.egg/EGG-INFO/scripts/xsser", line 24, in <module>
    from core.main import xsser
  File "/usr/local/lib/python2.7/dist-packages/xsser-1.7-py2.7.egg/core/main.py", line 35, in <module>
    from core.curlcontrol import Curl
  File "/usr/local/lib/python2.7/dist-packages/xsser-1.7-py2.7.egg/core/curlcontrol.py", line 24, in <module>
    import os, urllib, mimetools, pycurl, re, time, random
ImportError: No module named pycurl`

**Comment by epsylon** [comment]
> No module named pycurl

https://ufonet.03c8.net/#installation

sudo apt-get install python-pycurl

**Comment by epsylon** [comment]
This link I have provided you is for UFONet but library used: python-pycurl is same

**Comment by TylerByte666** [comment]
I can confirm that the issue still exists.

From this [guide](https://installlion.com/kali/kali/main/x/xsser/install/index.html):

`
sudo apt-get install xsser
`

... worked for me ❤️

**Comment by epsylon** [comment]
Ok @TylerByte666, but this is beacuse you are in Kali Linux and XSSer is on their repositories. I think version, 1.7-1-0kali2. So you are installing the whole package. Much better to try to clone it from here, mostly because we are currently on version 1.8.2-0, which is Python3 supported. So you probably will can to install it from scratch without any issue.

**Comment by TylerByte666** [comment]
Thanks blood! Much ❤️
