### ISSUE TITLE
Cannot install XSSer on Kali Linux (2019.4) x64bit

### ISSUE THREAD

**Issue by TylerByte666** [epsylon/xsser#49]
**Describe the bug**
Cannot install XSSer on Kali 2019.4

**To Reproduce**
1. Run `git clone git clone https://code.03c8.net/epsylon/xsser`
2. Run `python setup.py install `
3. Run `apt-get install python3-pycurl python3-bs4 python3-geoip python3-geoip2 python3-cairocffi`
4. Run` xsser -h`

**Error**
```
root@VB-Unkl3K4L1:~/Desktop/HellRoom/xsser# xsser -h
Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 4, in <module>
    __import__('pkg_resources').run_script('xsser==1.8', 'xsser')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/xsser-1.8-py2.7.egg/EGG-INFO/scripts/xsser", line 22, in <module>
    from core.main import xsser
  File "/usr/local/lib/python2.7/dist-packages/xsser-1.8-py2.7.egg/core/main.py", line 22, in <module>
    import os, re, sys, datetime, hashlib, time, urllib.request, urllib.parse, urllib.error, cgi, traceback, webbrowser, random
ImportError: No module named request
```

**Expected behavior**
To be shown XSSer help page.

**Running environment:**
 - XSSer version [1.8.2]
 - Installation method [git clone]
 - Operating system: [Kali Linux 2019.4 26 November 2019 x64 bit]
 - Python version [2.7.17]

**Additional context**
Fresh Kali install.

---

**Comment by epsylon** [comment]
Python 2.X.X is not longer supported... Please try: Python3.5.x

**Comment by TylerByte666** [comment]
I shall give it a go thanks

**Comment by TylerByte666** [comment]
I solved my problem by installing it using in the built in python3 that comes with a KaliLinux (2019.4):

**Command:** `python3 --version`
**Output**: `Python 3.7.5`
### Kali 2019.4 Installation Steps:
1. `apt-get install python3-pip`
2. `pip3 install pycurl bs4 geoip2 gobject cairocffi`
3. `git clone https://github.com/epsylon/xsser.git`
4. `cd xsser`
5. `python3 setup.py install`

Hope this helps somebody ❤️

**Comment by TylerByte666** [comment]
It stopped working now. I get the output: 
```
root@VB-Unkl3K4l1:~# xsser -h
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/curlcontrol.py", line 47, in Curl
    f = open("core/fuzzing/user-agents.txt").readlines() # set path for user-agents
FileNotFoundError: [Errno 2] No such file or directory: 'core/fuzzing/user-agents.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 4, in <module>
    __import__('pkg_resources').run_script('xsser==1.8', 'xsser')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/EGG-INFO/scripts/xsser", line 22, in <module>
    from core.main import xsser
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/main.py", line 34, in <module>
    from core.curlcontrol import Curl
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/curlcontrol.py", line 25, in <module>
    class Curl:
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/curlcontrol.py", line 49, in Curl
    f = open("fuzzing/user-agents.txt").readlines() # set path for user-agents when testing
FileNotFoundError: [Errno 2] No such file or directory: 'fuzzing/user-agents.txt'
```

**Comment by TylerByte666** [comment]
Then re-installing it worked.
I was able to run `xsser -h`

But when trying to Launch the GUI` xsser -h` I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 4, in <module>
    __import__('pkg_resources').run_script('xsser==1.8', 'xsser')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/EGG-INFO/scripts/xsser", line 35, in <module>
    app.run()
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/main.py", line 2621, in run
    self.create_gtk_interface()
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/main.py", line 2545, in create_gtk_interface
    from core.gtkcontroller import Controller, reactor
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/gtkcontroller.py", line 49, in <module>
    from core.globalmap import GlobalMap
  File "/usr/local/lib/python3.7/dist-packages/xsser-1.8-py3.7.egg/core/globalmap.py", line 47, in <module>
    import GeoIP
ModuleNotFoundError: No module named 'GeoIP'
```

To fix this I ran 

`apt-get install python3-pycurl python3-bs4 python3-geoip python3-geoip2 python3-gi python3-cairocffi`

I fixed the above solution to include the proper way of installing this awesome tool. I almost gave up on her there 😢
