### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by qszx** [epsylon/xsser#72]
kali2021.1
Python3.9
XSSer v1.8[3]: "The HiV€!" - (https://xsser.03c8.net) - 2010/2020 -> by psy
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/share/xsser/core/gtkcontroller.py", line 1994, in run
    self.app.run(self._cmd[1:])
  File "/usr/share/xsser/core/main.py", line 2973, in run
    self.poll_workers()
  File "/usr/share/xsser/core/main.py", line 2484, in poll_workers
    self.pool.poll()
  File "/usr/share/xsser/core/threadpool.py", line 358, in poll
    request.callback(request, result)
  File "/usr/share/xsser/core/main.py", line 928, in _cb
    self.finish_attack_url_payload(c, request, result, payload,
  File "/usr/share/xsser/core/main.py", line 1044, in finish_attack_url_payload
    self._report_attack_success(c, dest_url, payload,
  File "/usr/share/xsser/core/main.py", line 1440, in _report_attack_success
    self.check_hash_on_target(hashing, dest_url, orig_url, payload, query_string, method, curl_handle)                            
  File "/usr/share/xsser/core/main.py", line 1458, in check_hash_on_target
    self.check_hash_using_dom(dest_url, payload, hashing, query_string, orig_url, method) # check hash using internal headless browser engine
  File "/usr/share/xsser/core/main.py", line 1467, in check_hash_using_dom
    self.generate_headless_cookies(orig_url)
  File "/usr/share/xsser/core/main.py", line 1721, in generate_headless_cookies
    self.driver.get(orig_url)
AttributeError: 'NoneType' object has no attribute 'get'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
TypeError: Couldn't find foreign struct converter for 'cairo.Context'

**Comment by epsylon** [comment]
@qszx -> https://stackoverflow.com/questions/42279510/couldnt-find-foreign-struct-converter-for-cairo-context

**sudo apt-get install python-gi-cairo**

**Comment by epsylon** [comment]
For Python3:

**sudo apt-get install python3-gi-cairo**

Also, this error:

`AttributeError: 'NoneType' object has no attribute 'get'`

Should be fixed after this commit:

https://github.com/epsylon/xsser/commit/478242e6d8e1ca921e0ba8fa59b50106fa2f7312
