### ISSUE TITLE
print result bug INT

### ISSUE THREAD

**Issue by sanvilscript** [epsylon/xsser#78]
**Describe the bug**

Traceback (most recent call last):
  File "xsser", line 35, in <module>
    app.run()
  File "/usr/share/xsser/core/main.py", line 2742, in run
    self.print_results()
  File "/usr/share/xsser/core/main.py", line 3411, in print_results
    if self.options.threads > 9:
TypeError: '>' not supported between instances of 'str' and 'int'

fix
 if int(self.options.threads) > 9:

**Comment by epsylon** [comment]
@sanvilscript which version of XSSer are you using?

core/main.py -> Line 3411 -> https://github.com/epsylon/xsser/blob/master/core/main.py#L3411

Try to update the tool: **xsser --update**
